### ISSUE TITLE
Fails do build with poppler 22.01.0

### ISSUE THREAD

**Issue by lazka** [OSGeo/gdal#5071]
poppler 22.01.0 now requires c++17 and clang still defaults to c++14, which leads to things like this when rebuilding gdal:

```
2022-01-07T13:25:45.6529314Z D:/a/msys64/clang32/include/poppler/Form.h:320:10: error: no template named 'optional' in namespace 'std'
2022-01-07T13:25:45.6530403Z     std::optional<GooString> getCheckedSignature(Goffset *checkedFileSize);
2022-01-07T13:25:45.6531143Z     ~~~~~^
2022-01-07T13:25:45.6682481Z D:/a/msys64/clang32/include/poppler/Form.h:611:10: error: no template named 'optional' in namespace 'std'
2022-01-07T13:25:45.6684003Z     std::optional<GooString> getCheckedSignature(Goffset *checkedFileSize);
2022-01-07T13:25:45.6684763Z     ~~~~~^
```

See https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/1027#note_1211997

**Comment by lazka** [comment]
Thanks!
