### ISSUE TITLE
Fails to build with HDF 4.4.0

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#15165]
### What is the bug?

GDAL fails to build with HDF 4.4.0 as reported in [Debian Bug #1146650](https://bugs.debian.org/1146650):
> Your package FTBFS with HDF 4.4.0:
> ```
> /build/gdal-3.13.3+dfsg/frmts/hdf4/hdf-eos/EHapi.c: In function 'EHinquire':
> /build/gdal-3.13.3+dfsg/frmts/hdf4/hdf-eos/EHapi.c:2042:9: error: too few arguments to function 'Vgetclass'; expected 3, have 2
>  2042 |         Vgetclass(vGrpID, class);
>       |         ^~~~~~~~~
> In file included from /usr/include/hdf/hdf.h:192,
>                  from /usr/include/hdf/mfhdf.h:22,
>                  from /build/gdal-3.13.3+dfsg/frmts/hdf4/hdf-eos/EHapi.c:21:
> /usr/include/hdf/hproto.h:1407:15: note: declared here
>  1407 | HDFLIBAPI int Vgetclass(int32 vkey, char *vgclass, size_t *buf_size);
>       |               ^~~~~~~~~
> ```
> The full buildlog is attached.
[gdal_3.13.3+dfsg-2_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1146650;filename=gdal_3.13.3%2Bdfsg-2_amd64.build;msg=5)

### Steps to reproduce the issue

Build GDAL with HDF4 support enabled using HDF 4.4.0.

### Versions and provenance

Debian unstable

**Comment by rouault** [comment]
duplicate of #15126 . backport to 3.13 per https://github.com/OSGeo/gdal/commit/f8633d48ba49219f8d4285405b66949fe64be1f4
