### ISSUE TITLE
2.x branches that would build with GCC 9 fail to build with GCC 11 (error: ‘numeric_limits’ is not a member of ‘std’)

### ISSUE THREAD

**Issue by rpl-richard-lang** [OSGeo/gdal#8693]
I believe this is the same problem described in https://github.com/OSGeo/gdal/issues/5694 (although I'm seeing it in a normal/default x86 build on Ubuntu 22.04), and the root cause is discussed at https://gcc.gnu.org/gcc-11/porting_to.html#header-dep-changes - anachronistic use of some std namespace classes without directly #include-ing the appropriate header files, which was tolerated by GCC versions prior to 11 but no longer is.

In my case I'm using GDAL 2.3 in a 6 year old mature project that was previously built on a Ubuntu 20.04 host machine (default GCC 9 from `build-essentials` package), however on recently upgrading the host machine to Ubuntu 22.04  `build-essentials` defaults to providing GCC 11.

This was fixed in https://github.com/OSGeo/gdal/commit/d778082534a0bf5b6fc23691d37865b28553662c, however the fix is only available in GDAL 3.7 onwards.   This leaves any projects using v. 2.x GDAL built from source unable to be built on current Debian build hosts using the default compiler, and GDAL 3.x does not appear to be a simple drop-in replacement for 2.x (shift from AutoTools to CMake for a start, let alone any compile-time API changes that I've yet to discover)

Perhaps this would justify a v2.5 release with the fix back-ported?

**Comment by rpl-richard-lang** [comment]
I'm not aware of any work-around, in particular passing GCC a `-std=c++11` argument doesn't seem to change anything

**Comment by rpl-richard-lang** [comment]
spoke too soon,  passing GCC a `-include limits` argument suppresses the error and allows a successful build

**Comment by jratike80** [comment]
Glad to hear that. The GDAL project supports only one branch that is now 3.7 and next week 3.8. Version 3.0 was released May 9, 2019. It is unlikely that GDAL 2.x series will receive any back-ports.

**Comment by rouault** [comment]
yes we won't do any 2.x release any more. This is free software: you can maintain your own patches to meet your specific needs & goals. Closing as won't fix
