### ISSUE TITLE
Error while creating CSV file from a shapefile using ogr2ogr.java in java application

### ISSUE THREAD

**Issue by aswiniy** [OSGeo/gdal#1713]
Hello GDAL Team,

I am a new gdal user. I would like to import a shapefile to our system by converting it to a CSV file in java . So we have downloaded the gdal.jar from [here](https://jar-download.com/artifacts/org.gdal/gdal/3.0.0/source-code) and run the ogr2ogr.java using the gdal.jar ( Both are from version 3.0.0) and it compiled with no errors. But during execution, we got errors, that native libraries are missing. So on further analysis, we understood that it needs some native libraries as mentioned [here](https://trac.osgeo.org/gdal/wiki/GdalOgrInJavaBuildInstructionsUnix) which says,   “To deploy you need gdal.jar in your class path, the 4 .so files (libgdalconstjni.so, libgdaljni.so, libogrjni.so and libosrjni.so) and libgdal.so in your shared library path.”

We have checked for those library files in your repository, but we could not find them/any help documentations to generate them. Finally we have downloaded those library files (we could find only for linux) from some external sources and with these library files in Djava.library.path, we have executed the ogr2ogr.java. It showed an error like “ Native Library gdalalljni.so is missing” . We got it from third party source [here](https://github.com/nasa/World-Wind-Java/tree/master/WorldWind/lib-external/gdal) as we could not generate this library file too. Now, executing the ogr2ogr.jave will all the above said 4 *.so files along with gdalalljni.so still shows the below error.

Exception in thread "main" java.lang.UnsatisfiedLinkError: org.gdal.ogr.ogrJNI.RegisterAll()

at org.gdal.ogr.ogrJNI.RegisterAll(Native Method)

at org.gdal.ogr.ogr.RegisterAll(ogr.java:90)

at ogr2ogr.main(ogr2ogr.java:116)

we have also tried with 1.7.3 version (gdal.jar and ogr2.ogr.java and library files) but the error still exists.

We request you to help us with any misconceptions in our understanding/working procedure and also in generation of library files and a detailed help documentation to run the  ogr2ogr.java with out any errors to generate a CSV file .

Thank you in advance.

## Operating system
We are working in Linux 18.04
PS: we need this to be working for mac,linux,windows and centos machines.

## GDAL version and provenance
 GDAL version used - 3.0.0

**Comment by rouault** [comment]
You need to use the gdal.jar, gdalalljni.so and libgdal.so from the same GDAL version
To build gdal.jar and gdalalljni.so from sources, build the GDAL native library the classic way ./configure && make and then
cd swig/java
make

**Comment by aswiniy** [comment]
Hi rouault,

When we run ./configure we are getting the below error.

checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
using ICONV_CPP_CONST=""
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
configure: error: PROJ 6 symbols not found

**Comment by aswiniy** [comment]
I am getting below error while executing make in gdal folder. Please help if i am doing something wrong. I am using Proj6 and ./configure got executed without any errors.

/Library/Developer/CommandLineTools/usr/bin/make -C postgisraster install-obj
/bin/sh /Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/libtool --mode=compile --silent --tag=CXX g++ -std=c++11 -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/gcore -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/alg -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/ogr -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/ogr/ogrsf_frmts -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/gnm -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/apps -Weffc++ -Wold-style-cast -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough  -I ../mem -I ../vrt  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/include   -DGNM_ENABLED -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/local/include -I/usr/local/include/xercesc -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -c -o ../o/postgisrasterdriver.lo postgisrasterdriver.cpp
In file included from postgisrasterdriver.cpp:31:
./postgisraster.h:41:10: fatal error: 'libpq-fe.h' file not found
#include "libpq-fe.h"
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [../o/postgisrasterdriver.lo] Error 1
make[1]: *** [postgisraster-install-obj] Error 2
make: *** [frmts-target] Error 2

Thanks.

**Comment by filislav** [comment]
Hello GDAL team. Is your library works on mac os 10.15.x ? How i may to create gdalalljni.dylib for mac os?
