### ISSUE TITLE
Build with ECW SDK5.5 link error.

### ISSUE THREAD

**Issue by hello-willy** [OSGeo/gdal#4727]
hi all:
    I want to build gdal2.2.4 with ecw sdk 5.5, in centos7.
    
the build command that i used is below
 ./configure --with-ecw=/root/hexagon/ERDAS-ECW_JPEG_2000_SDK-5.5.0/Desktop_Read-Only

at last occur error as below
undefined reference to `NCS:CString::Utf8Encode(std::__cxx11::basic_string<char, std::char_traits<char>,std::allocator<char> const&)`

undefined reference to `NCS::CView::SetTransformList(int, std::__cxx11::list<NCS::API::ITransform`....

PS:gcc's version is 7.3.0

what's problem? i need help, pls!!! 
Thank YOU!!!!

**Comment by hello-willy** [comment]
> ECW SDK 5.4 apparently, but we don't support anything older than GDAL 3.3 now, and in a few days 3.4

thank you sir!!!! very much!
