### ISSUE TITLE
build failure with poppler 0.73

### ISSUE THREAD

**Issue by jbicha** [OSGeo/gdal#1325]
Please see https://github.com/OSGeo/gdal/issues/1208 which is a similar bug but there are enough remaining issues, I thought it best to open a new bug.

I believe there is a logic error in the  `gdal/frmts/pdf/pdfsdk_headers.h` part of d295d0e

Switch the `#include` and `typedef` lines.

I believe gdal still fails to build with poppler 0.73 after that fix, but I have run out of time to look into it more closely. Now that poppler 0.73 has been released, it might be easier for you to do a test build yourself to make sure things work.

Here's one build error:
```
pdfdataset.cpp: In member function ‘void PDFDataset::FindLayersPoppler()’:
pdfdataset.cpp:3465:73: error: ‘const class GooString’ has no member named ‘getCString’;
 did you mean ‘GooString’?
```

**Comment by rouault** [comment]
Please check that you are using the latest state of master or release/2.4 branch. I've just tested they compile fine against Poppler 0.73.0

**Comment by rouault** [comment]
To be clear: there is not yet any released GDAL versions that is compatible of 0.73.0 (the first one will be GDAL 2.4.1 unreleased now)

**Comment by rouault** [comment]
Assuming GDAL 2.4.0 was used instead of latest git version, closing
