### ISSUE TITLE
ECW 5.5 Update 1 fails to compile on GDAL 3.1.0

### ISSUE THREAD

**Issue by sweco-nlmrag** [OSGeo/gdal#2738]
Hi,

I'm posting this as per requested by @jbowman-hexagon in https://github.com/OSGeo/gdal/pull/2652#issuecomment-652842541

The build environment is as follows:
Windows 10 32 bit
Visual Studio 2017 (version 15.9.21)

Then I successfully compiled GDAL. I had provided the following relevant ECW detail in that file:
```
# Uncomment the following and update to enable ECW read support with the 5.0+ SDK
ECWDIR  =  $(COMPONENTSDIR)\ECW\5_5_u1
ECWINCDIR = $(ECWDIR)\include
ECWFLAGS = -DECWSDK_VERSION=50 \
       -I$(ECWINCDIR) \
       -I$(ECWINCDIR)/NCSEcw/api -I$(ECWINCDIR)/NCSEcw/jp2 \
       -I$(ECWINCDIR)/NCSEcw/ecw
ECWLIB  =  $(ECWDIR)\lib\vc141\Win32\NCSEcw.lib

# To build ECW support as a plugin uncomment the following, and make sure
# to do "nmake /f makefile.vc plugin" in gdal/frmts/ecw and copy the two
# resulting DLLs to an appropriate place.
ECW_PLUGIN = YES
```
Where `$(COMPONENTSDIR)\ECW\5_5_u1` translates to the directory where ECW 5.5 Update 1 is installed. This installer came from https://download.hexagongeospatial.com/downloads/ecw/erdas-ecw-jp2-sdk-v55-update-1-windows

After the GDAL compilation I enter the ECW folder and execute:
```
nmake /f makefile.vc plugin
```

As per the advice of nmake.opt to build the plugin.
This eventually gives me the following errors:
```
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(1067): error C2440: 'type cast': cannot convert from 'NCS::CIOStreamPtr' to 'VSIIOStream *'
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(1067): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(2558): error C2664: 'NCS::CError NCS::CView::Open(const NCS::CIOStreamPtr &,bool,NCSFileType)': cannot convert argument 1 from 'VSIIOStream *' to 'wchar_t *'
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(2558): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(2575): error C2440: 'type cast': cannot convert from 'NCS::CIOStreamPtr' to 'VSIIOStream *'
d:\jenkins_work\workspace\gdal_3.1.0\gdal-3.1.0\frmts\ecw\ecwdataset.cpp(2575): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
NMAKE : fatal error U1077: 'cl' : return code '0x2'
Stop.
	cd ..
	cd ogr\ogrsf_frmts
	nmake /nologo /f makefile.vc plugindirs
plugins: dwg oci
	for %d in (   dwg          oci             ) do  cd %d  && nmake /nologo /f makefile.vc plugin  && cd ..  || exit 1
```

The nature of the errors like `error C2440: 'type cast': cannot convert from 'NCS::CIOStreamPtr' to 'VSIIOStream *'` make me think that i have setup the environment and paths correctly.

Is there any more information that you'd want me to share?

Note, i can update GDAL to 3.1.1 is that is required. But i prefer to just get this working before updating GDAL.

Best regards,
Mark

**Comment by rouault** [comment]
> -DECWSDK_VERSION=50

I believe you should try with -DECWSDK_VERSION=55 as this is version 5.5 of the SDK

**Comment by sweco-nlmrag** [comment]
> > -DECWSDK_VERSION=50
> 
> I believe you should try with -DECWSDK_VERSION=55 as this is version 5.5 of the SDK

Ahh, that did the trick :)
Note that the nmake documentation made me give the wrong assumption here.
It tells me:
`# Uncomment the following and update to enable ECW read support with the 5.0+ SDK`

Which i interpreted as "i suppose setting `ECWFLAGS = -DECWSDK_VERSION=50` works for 5.0 and up then".

It now works as expected.
