### ISSUE TITLE
GDAL-3.12.4 fails to build with poppler 26.0.6

### ISSUE THREAD

**Issue by xelaseer** [OSGeo/gdal#14714]
### What is the bug?

As per the above, GDAL-3.12.4 fails to build with poppler-26.0.6.

Please see the attached build.log.

### Steps to reproduce the issue

1. Build GDAL-3.12.4 with poppler-26.0.6.
2. Fails with error.

### Versions and provenance

Gentoo Linux - Latest ~amd64 - pg_overlay repository. - systemd/gnome stack.

Gdal-3.12.4

Poppler-26.0.6

### Additional context

[build.log](https://github.com/user-attachments/files/28583905/build.log)

[emerge-info.txt](https://github.com/user-attachments/files/28583909/emerge-info.txt)

**Comment by jef-n** [comment]
fixed in #14588

**Comment by xelaseer** [comment]
This patchset unfortunately did not resolve the issue. I am getting a new error:


[build.log](https://github.com/user-attachments/files/28623888/build.log)

**Comment by xelaseer** [comment]
See for example:

In file included from /var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp:20:
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/gdal_pdf.h:280:38: error: ‘OptionalContentGroup’ was not declared in this scope
  280 |     std::vector<std::pair<CPLString, OptionalContentGroup *>>
      |                                      ^~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/gdal_pdf.h:280:59: error: template argument 2 is invalid
  280 |     std::vector<std::pair<CPLString, OptionalContentGroup *>>
      |                                                           ^
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/gdal_pdf.h:280:60: error: template argument 1 is invalid
  280 |     std::vector<std::pair<CPLString, OptionalContentGroup *>>
      |                                                            ^~
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/gdal_pdf.h:280:60: error: template argument 2 is invalid
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp: In member function ‘void PDFDataset::ExploreLayersPoppler(GDALPDFArray*, int, int, CPLString, int, int&, bool&)’:
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp:3751:13: error: ‘m_oLayerOCGListPoppler’ was not declared in this scope
 3751 |             m_oLayerOCGListPoppler.push_back(std::pair(osTopLayer, nullptr));
      |             ^~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp:3789:17: error: ‘OptionalContentGroup’ was not declared in this scope
 3789 |                 OptionalContentGroup *ocg = optContentConfig->findOcgByRef(r);
      |                 ^~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp:3789:39: error: ‘ocg’ was not declared in this scope
 3789 |                 OptionalContentGroup *ocg = optContentConfig->findOcgByRef(r);
      |                                       ^~~
/var/tmp/portage/sci-libs/gdal-3.12.4/work/gdal-3.12.4/frmts/pdf/pdfdataset.cpp:3789:61: error: invalid use of incomplete type ‘const class OCGs’
 3789 |                 OptionalContentGroup *ocg = optContentConfig->findOcgByRef(r);

**Comment by jef-n** [comment]
there are more fixes (my excerpt was https://github.com/jef-n/OSGeo4W/blob/c3b883062e522ac2c86919b96c2960255f2192de/src/gdal/osgeo4w/patch - but 3.13.1 was just released which includes them).
