### PR TITLE
ogr2ogr: fix compilation error with Crypto++ 7.0.0 (fix #541)

### LINKED ISSUE #541: Cannot compile gdal 2.2.4 with crypto++ 7.0.0 on Arch Linux
## Description
I tried to build gdal on Arch Linux with crypto++ 7.0.0 installed. My default compiler is clang/clang++.  `make` command fails on `port/cpl_vsil_crypt.cpp`. I created a patch to mitigate this.

## Steps to reproduce the problem.

I downloaded the PKGBUILD file from this [Arch package page](https://www.archlinux.org/packages/community/x86_64/gdal/). (enter and click "Download From Mirror") If you're familiar with Arch, you can follow the snippet to create a gdal package from source. It automatically runs the building instructions in [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/gdal).
```sh
yaourt -G gdal
cd gdal/
makepkg -C -L
```

The build process fails on `make` step with the message.
```
cpl_vsil_crypt.cpp:450:34: error: unknown type name 'byte'; did you mean 'CryptoPP::byte'?
            *poEncCipher, (const byte*)osCheckIV.c_str());
                                 ^~~~
                                 CryptoPP::byte
/usr/include/cryptopp/config.h:237:23: note: 'CryptoPP::byte' declared here
typedef unsigned char byte;
                      ^
cpl_vsil_crypt.cpp:458:32: error: unknown type name 'byte'; did you mean 'CryptoPP::byte'?
        reinterpret_cast<const byte*>(
                               ^~~~
                               CryptoPP::byte
/usr/include/cryptopp/config.h:237:23: note: 'CryptoPP::byte' declared here
typedef unsigned char byte;
                      ^
cpl_vsil_crypt.cpp:595:44: error: unknown type name 'byte'; did you mean 'CryptoPP::byte'?
                poEncCipher->SetKey((const byte*)osKey.c_str(), nKeySize);
                                           ^~~~
                                           CryptoPP::byte
```

Though I switch to gcc/g++, it doesn't work as well. It seems gdal cannot build with newer Crypto++ 7.0.0. I created this patch to replace every `byte` to `CryptoPP::byte` to resolve it.
```diff
--- a/port/cpl_vsil_crypt.cpp	2018-04-29 22:46:41.700797075 +0800
+++ b/port/cpl_vsil_crypt.cpp	2018-04-29 22:46:51.497625218 +0800
@@ -447,7 +447,7 @@
     CryptoPP::StringSink* poSink = new CryptoPP::StringSink(osKeyCheckRes);
     CryptoPP::StreamTransformation* poMode =
         new CryptoPP::CBC_Mode_ExternalCipher::Encryption(
-            *poEncCipher, (const byte*)osCheckIV.c_str());
+            *poEncCipher, (const CryptoPP::byte*)osCheckIV.c_str());
     CryptoPP::StreamTransformationFilter* poEnc =
         new CryptoPP::StreamTransformationFilter(
             *poMode, poSink,
@@ -455,7 +455,7 @@
     // Not sure if it is add extra security, but pick up something that is
     // unlikely to be a plain text (random number).
     poEnc->Put(
-        reinterpret_cast<const byte*>(
+        reinterpret_cast<const CryptoPP::byte*>(
             "\xDB\x31\xB9\x1B\xD3\x1C\xFA\x3E\x84\x06\xC1\x42\xC3\xEC\xCD\x9A"
             "\x02\x36\x22\x15\x58\x88\x74\x65\x00\x2F\x98\xBC\x69\x22\xE1\x63"),
         std::min(32U, poEncCipher->BlockSize()));
@@ -592,7 +592,7 @@
             {
                 const int nKeySize =
                     std::min(nMaxKeySize, static_cast<int>(osKey.size()));
-                poEncCipher->SetKey((const byte*)osKey.c_str(), nKeySize);
+                poEncCipher->SetKey((const CryptoPP::byte*)osKey.c_str(), nKeySize);
             }
             else if( pabyGlobalKey )
             {
@@ -845,8 +845,8 @@
         {
             const int nKeySize =
                 std::min(nMaxKeySize, static_cast<int>(osKey.size()));
-            poEncCipher->SetKey((const byte*)osKey.c_str(), nKeySize);
-            poDecCipher->SetKey((const byte*)osKey.c_str(), nKeySize);
+            poEncCipher->SetKey((const CryptoPP::byte*)osKey.c_str(), nKeySize);
+            poDecCipher->SetKey((const CryptoPP::byte*)osKey.c_str(), nKeySize);
         }
         else if( pabyGlobalKey )
         {
@@ -905,19 +905,19 @@
     CryptoPP::StreamTransformation* poMode;
     if( poHeader->eMode == MODE_CBC )
         poMode = new CryptoPP::CBC_Mode_ExternalCipher::Encryption(
-            *poEncCipher, reinterpret_cast<const byte *>(osIV.c_str()) );
+            *poEncCipher, reinterpret_cast<const CryptoPP::byte *>(osIV.c_str()) );
     else if( poHeader->eMode == MODE_CFB )
         poMode = new CryptoPP::CFB_Mode_ExternalCipher::Encryption(
-            *poEncCipher, reinterpret_cast<const byte *>(osIV.c_str()) );
+            *poEncCipher, reinterpret_cast<const CryptoPP::byte *>(osIV.c_str()) );
     else if( poHeader->eMode == MODE_OFB )
         poMode = new CryptoPP::OFB_Mode_ExternalCipher::Encryption(
-            *poEncCipher, reinterpret_cast<const byte *>(osIV.c_str()) );
+            *poEncCipher, reinterpret_cast<const CryptoPP::byte *>(osIV.c_str()) );
     else if( poHeader->eMode == MODE_CTR )
         poMode = new CryptoPP::CTR_Mode_ExternalCipher::Encryption(
-            *poEncCipher, reinterpret_cast<const byte *>(osIV.c_str()) );
+            *poEncCipher, reinterpret_cast<const CryptoPP::byte *>(osIV.c_str()) );
     else
         poMode = new CryptoPP::CBC_CTS_Mode_ExternalCipher::Encryption(
-            *poEncCipher, reinterpret_cast<const byte *>(osIV.c_str()) );
+            *poEncCipher, reinterpret_cast<const CryptoPP::byte *>(osIV.c_str()) );
     CryptoPP::StreamTransformationFilter* poEnc =
         new CryptoPP::StreamTransformationFilter(
             *poMode, poSink, CryptoPP::StreamTransformationFilter::NO_PADDING);
@@ -949,22 +949,22 @@
         // Yes, some modes need the encryption cipher.
         if( poHeader->eMode == MODE_CBC )
             poMode = new CryptoPP::CBC_Mode_ExternalCipher::Decryption(
-                *poDecCipher, (const byte*)osIV.c_str() );
+                *poDecCipher, (const CryptoPP::byte*)osIV.c_str() );
         else if( poHeader->eMode == MODE_CFB )
             poMode = new CryptoPP::CFB_Mode_ExternalCipher::Decryption(
-                *poEncCipher, (const byte*)osIV.c_str() );
+                *poEncCipher, (const CryptoPP::byte*)osIV.c_str() );
         else if( poHeader->eMode == MODE_OFB )
             poMode = new CryptoPP::OFB_Mode_ExternalCipher::Decryption(
-                *poEncCipher, (const byte*)osIV.c_str() );
+                *poEncCipher, (const CryptoPP::byte*)osIV.c_str() );
         else if( poHeader->eMode == MODE_CTR )
             poMode = new CryptoPP::CTR_Mode_ExternalCipher::Decryption(
-                *poEncCipher, (const byte*)osIV.c_str() );
+                *poEncCipher, (const CryptoPP::byte*)osIV.c_str() );
         else
             poMode = new CryptoPP::CBC_CTS_Mode_ExternalCipher::Decryption(
-                *poDecCipher, (const byte*)osIV.c_str() );
+                *poDecCipher, (const CryptoPP::byte*)osIV.c_str() );
         poDec = new CryptoPP::StreamTransformationFilter(
             *poMode, poSink, CryptoPP::StreamTransformationFilter::NO_PADDING);
-        poDec->Put((const byte*)pabyData, poHeader->nSectorSize);
+        poDec->Put((const CryptoPP::byte*)pabyData, poHeader->nSectorSize);
         poDec->MessageEnd();
         delete poDec;
         delete poMode;
@@ -1242,7 +1242,7 @@
 #endif
                     // Fill with 0.
                     memset(
-                        (byte*)(pabyWB + poHeader->nPayloadFileSize -
+                        (CryptoPP::byte*)(pabyWB + poHeader->nPayloadFileSize -
                                 nLastSectorOffset),
                         0,
                         static_cast<int>(
@@ -1361,7 +1361,7 @@
 #endif
                 CryptoPP::OS_GenerateRandomBlock(
                     false, // Do not need cryptographic randomness.
-                    (byte*)(pabyWB +
+                    (CryptoPP::byte*)(pabyWB +
                             poHeader->nPayloadFileSize - nLastSectorOffset),
                     static_cast<int>(
                         poHeader->nSectorSize -
@@ -1654,7 +1654,7 @@
             osIV.resize(nBlockSize);
             CryptoPP::OS_GenerateRandomBlock(
                 false,  // Do not need cryptographic randomness.
-                (byte*)osIV.c_str(), osIV.size());
+                (CryptoPP::byte*)osIV.c_str(), osIV.size());
         }
 
         if( EQUAL(osKey, "GENERATE_IT") )
@@ -1667,7 +1667,7 @@
                 // Config option for speeding tests.
                 CPLTestBool(CPLGetConfigOption("VSICRYPT_CRYPTO_RANDOM",
                                                "TRUE")),
-                (byte*)osKey.c_str(), osKey.size());
+                (CryptoPP::byte*)osKey.c_str(), osKey.size());
 
             char* pszB64 = CPLBase64Encode(static_cast<int>(osKey.size()),
                                            (const GByte*)osKey.c_str());

```

## Operating system

OS: Arch Linux on a  x86_64 machine.
compiler: gcc/g++ or clang/clang++
packages: Crtpto++ 7.0.0

## GDAL version and provenance

gdal 2.2.4. The build script on [Arch Linux package page](https://www.archlinux.org/packages/community/x86_64/gdal/)

### PR DESCRIPTION
**Pull request by jerry73204**
This issue is fixed up by replacing byte type to CtyptoPP:byte in the following files:
gdal/port/cpl_sha256.cpp
gdal/port/cpl_vsil_crypt.cpp

## Environment
* OS: Arch Linux
* Compiler: gcc/g++

### CODE REVIEW

**Comment by rouault** [comment]
This breaks with older cryptopp : https://travis-ci.org/OSGeo/gdal/jobs/372912753
So some #ifdef conditional check based on the version of crypto++ will be needed

**Comment by jerry73204** [comment]
Some preprocessor checks are added. Now it should compile with Crypto++ 5/6/7.

**Comment by rouault** [comment]
Thanks !
