### ISSUE TITLE
Elastic driver build failure on manylinux1 image based on CentOS 5

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#3374]
## Expected behavior and actual behavior.

GDAL 3.2.1 does not compile on Rasterio's manylinux1 wheel building system based on CentOS 5, whereas 3.2.0 does.

Here's the error:

```
In file included from ogr_elastic.h:33:0,
                 from ogrelasticlayer.cpp:30:
/io/gdal-3.2.1/ogr/ogrsf_frmts/ogrsf_frmts.h: In lambda function:
/io/gdal-3.2.1/ogr/ogrsf_frmts/ogrsf_frmts.h:109:18: error: ‘OGRErr OGRLayer::GetExtentInternal(int, OGREnvelope*, int)’ is protected
     OGRErr       GetExtentInternal(int iGeomField, OGREnvelope *psExtent, int bForce );
                  ^
ogrelasticlayer.cpp:3513:83: error: within this context
         const auto eRet = OGRLayer::GetExtentInternal(iGeomField, psExtent, bForce);
```

I found that this driver did have changes between 3.2.0 and 3.2.1: https://github.com/OSGeo/gdal/commit/89906207f6212d45adbca88378c748f37262aa67.

## Steps to reproduce the problem.

Sorry, I've had to move rasterio's wheel building within a private fork in the Mapbox org because of Travis CI pricing changes.

I'll try to provide more details soon.

## Operating system

CentOS 5

## GDAL version and provenance

3.2.1 tarball from the download page.

**Comment by sgillies** [comment]
Configuring the GDAL build with `--disable-driver-elastic` is a workaround.

**Comment by rouault** [comment]
Weird. The release/3.2 branch builds fine on this Travis-CI Ubuntu 14.04 config (32 bit build, but that shouldn't matter) and it uses gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 : https://travis-ci.com/github/OSGeo/gdal/jobs/470097266
Anyway in master we don't test anymore Ubuntu 14.04 and gcc 4.8, so it might be time considering updating the build chain to something slightly less antiquated than gcc 4.8 :-)

**Comment by sgillies** [comment]
@rouault sorry about the misleading title. I tried to change it last night but must have failed to click the save button. Indeed, I do need to get onboard the manylinux2010/2014 train soon :)

**Comment by matthewhanson** [comment]
I've also got this error building GeoLambda with GDAL 3.2 (this is using an Amazon Linux base image).
It worked previously with GDAL 3.1.3.  (also bumped PROJ, libgeotiff and openjpeg).

Dockerfile here:
https://github.com/developmentseed/geolambda/blob/develop/Dockerfile

**Comment by sgillies** [comment]
Elastic's license change might make the driver a good candidate for removal anyway.

**Comment by rouault** [comment]
I should definitely have not backported that changeset to the stable branch. I knew it was a bad idea but did that to please my customer. That said it builds on all the CI configs we have, and some of them are really not super shiny... So yes people with gcc < 5 might run into bumps.

That said, the Elastic driver is probably still relevant. We will now have both the elastic.co and AWS team in a need for it lol ! Double maintained driver! yeah!!!!

**Comment by sgillies** [comment]
We should :hocho: the proprietary driver and insist (by mechanism yet to be defined) AWS maintain the open source driver.

**Comment by rouault** [comment]
closing as solved / no longer relevant
