### ISSUE TITLE
Problem reading XYZ with gdal.Open in Python

### ISSUE THREAD

**Issue by Vasshus** [OSGeo/gdal#7096]
## Expected behavior and actual behavior.

I expected to be able to open this XYZ raster file; However it returns an error message instead.

**ERROR 1: Ungridded dataset: At line 195, too many stepY values**

The dataset is a grid and looks like like this (0.5 x 0.5 meter):

![image](https://user-images.githubusercontent.com/48474588/213371116-bae3681e-34d2-4818-a471-aff5b14e8ba1.png)

Attached is the example file: [test.zip](https://github.com/OSGeo/gdal/files/10454091/test.zip)

## Steps to reproduce the problem.

```
from osgeo import gdal
ds = gdal.Open(r"D:\Temp\test.xyz")

```
**ERROR 1: Ungridded dataset: At line 195, too many stepY values**

## Operating system
Windows 10 ver. 22H2
Python 3.9.11 [MSC v.1931 64 bit (AMD64)] :: Anaconda, Inc. on win32

## GDAL version and provenance

3.4.0 Version

**Comment by jratike80** [comment]
I can't repeat the error with gdalinfo, gdal_translate, or Python with OSGeoW4, GDAL version GDAL 3.6.2, released 2023/01/02. What is your GDAL version?

**Comment by Vasshus** [comment]
I'm running tis in ArcGIS PRO

![image](https://user-images.githubusercontent.com/48474588/213380514-cc93c3b3-7a16-429e-8803-f08b2cb68773.png)

**Comment by jratike80** [comment]
ESRI is using their own GDAL version. Send a question to your local ESRI support and them. Prove them that the community GDAL can open your dataset (install the same 3.4.1 version for you). They may start investigating your case but that is all but sure. XYZ does not seem to be officially supported https://pro.arcgis.com/en/pro-app/latest/help/data/imagery/supported-raster-dataset-file-formats.htm and I could not open the test.xyz file with ArcGIS Pro desktop either.

Meanwhile you can use QGIS that opens the test.xyz file withour problem.

**Comment by Vasshus** [comment]
I tested this code in QGIS 3.28.1-Firenze

from osgeo import gdal
import sys
ds = gdal.Open(r"D:\Temp\test.xyz")
print(type (ds))
<class 'NoneType'>
print(gdal.__version__)
3.6.0
print(sys.version)
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

Reading the file gives me a None object

**Comment by jratike80** [comment]
And this is for me, now with GDAL 3.7.0dev-5ccdf5fb39, released 2023/01/09


```
from osgeo import gdal
import sys
ds = gdal.Open("test.xyz")
print(type (ds))
<class 'osgeo.gdal.Dataset'>
print(gdal.version)
AttributeError: module 'osgeo.gdal' has no attribute 'version'
print(sys.version)
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
```

**Comment by rouault** [comment]
This works in 3.6.2 and 3.7.0dev. There have been significant fixes in the XYZ driver in 3.6.1 (#6736), so I assume they have fixed that one. Closing
