### ISSUE TITLE
jpeg2000_vsil_io.cpp:151:5: error: cannot initialize a member subobject of type 

### ISSUE THREAD

**Issue by filislav** [OSGeo/gdal#2977]
## Expected behavior and actual behavior.

jpeg2000_vsil_io.cpp:151:5: error: cannot initialize a member subobject of type 'int (*)(jas_stream_obj_t *,
      const char *, unsigned int)' (aka 'int (*)(void *, const char *, unsigned int)') with an lvalue of type
      'int (jas_stream_obj_t *, char *, unsigned int)' (aka 'int (void *, char *, unsigned int)'): type
      mismatch at 2nd parameter ('const char *' vs 'char *')
    JPEG2000_VSIL_write,

## Steps to reproduce the problem.

I am trying to make gdalalljni on mac os 10.15.7. When i run "make" command after install all required libraries compiler writes me this message. And i don't have gdal/gdal/libgdal.la that nesessary for make buildings in swig/java.  **Please answer, is it possible to work with gdal on macos 10.15.7 or not ?** When i run my application in NetBeansIDE i get: 

Native library load failed.
java.lang.UnsatisfiedLinkError: no gdalalljni in java.library.path: [/Users/slava/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 'void org.gdal.gdal.gdalJNI.AllRegister()'
	at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
	at org.gdal.gdal.gdal.AllRegister(gdal.java:571)
	at ru.soniir.tropo.tropolinecalc.topograph.GeoTiffTopograph.<init>(GeoTiffTopograph.java:45)
	at ru.soniir.tropo.tropolinecalc.pojo.Track.<clinit>(Track.java:40)
	at ru.soniir.tropo.tropolinecalc.gui.MainFrame.<init>(MainFrame.java:57)
	at ru.soniir.tropo.tropolinecalc.TropoLineCalc$1.run(TropoLineCalc.java:26)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

## Operating system
MacOS 10.15.7

## GDAL version and provenance

2.4.0

**Comment by rouault** [comment]
This has been fixed in 3.1.3. See commits ab72c4893e6d14d488dfed25745d79f11bee45b9 and e236eeaed1be45a4af457565085e3db1f2fc489f
