### ISSUE TITLE
Fails to build with poppler 0.69.0

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#1004]
As reported by Emilio Pozuelo Monfort in [Debian Bug #910872](https://bugs.debian.org/910872):
> Your package fails to build against poppler 0.69, currently in experimental.
> In some cases there are patches in Ubuntu, the PTS has links.
> 
> For the memCheck errors, you can just patch out those calls, those were
> noops anyway as we didn't build with DEBUG_MEM, see
> 
> https://cgit.freedesktop.org/poppler/poppler/commit/?id=c362ab1b97f20c5b73b3bad8d52015f679178748
> 
> I intend to update our poppler soon as there are some security fixes
> in the newer versions. I'd appreciate if you can take a look at this
> and apply any necessary fixes.
> 
> Full build log attached.

[gdal_2.3.2+dfsg-1_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=910872;filename=gdal_2.3.2%2Bdfsg-1_amd64.build;msg=5)

Error from the buidlog:
```
pdfdataset.cpp: In member function 'void PDFDataset::FindLayersPoppler()':
pdfdataset.cpp:3443:54: error: cannot convert 'const std::unordered_map<Ref, std::unique_ptr<OptionalContentGroup> >' to 'GooList*' in initialization
         GooList* ocgList = optContentConfig->getOCGs();
                                                      ^
pdfdataset.cpp: In member function 'void PDFDataset::TurnLayersOnOffPoppler()':
pdfdataset.cpp:3475:54: error: cannot convert 'const std::unordered_map<Ref, std::unique_ptr<OptionalContentGroup> >' to 'GooList*' in initialization
         GooList* ocgList = optContentConfig->getOCGs();
                                                      ^
```

## Operating system

Debian unstable

## GDAL version and provenance

GDAL 2.3.2 from Debian unstable
