### ISSUE TITLE
Add libtirpc to new cmake system - DODS and OGDI drivers fail to build on Ubuntu21.10

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#4817]
This is a similar issue to
https://github.com/OSGeo/gdal/pull/4394#issuecomment-908892817

## Expected behavior and actual behavior.
Build from git head using cmake.
Expected all drivers to build.
Actual: OGDI and DODS (raster and vector) drivers fail to build because rpc/types.h is not found.

[ 45%] Building CXX object frmts/dods/CMakeFiles/gdal_DODS.dir/dodsdataset2.cpp.o
In file included from /usr/include/libdap/XDRUtils.h:37,
                 from /usr/include/libdap/Sequence.h:50,
                 from /home/werdna/git/gdal/frmts/dods/libdap_headers.h:50,
                 from /home/werdna/git/gdal/frmts/dods/dodsdataset2.cpp:38:
/usr/include/libdap/xdr-datatypes.h:16:10: fatal error: rpc/types.h: No such file or directory
   16 | #include <rpc/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

[ 71%] Building CXX object ogr/ogrsf_frmts/dods/CMakeFiles/ogr_DODS.dir/ogrdodsdatasource.cpp.o
In file included from /usr/include/libdap/XDRUtils.h:37,
                 from /usr/include/libdap/Sequence.h:50,
                 from /home/werdna/git/gdal/ogr/ogrsf_frmts/dods/libdap_headers.h:52,
                 from /home/werdna/git/gdal/ogr/ogrsf_frmts/dods/ogr_dods.h:44,
                 from /home/werdna/git/gdal/ogr/ogrsf_frmts/dods/ogrdodsdatasource.cpp:30:
/usr/include/libdap/xdr-datatypes.h:16:10: fatal error: rpc/types.h: No such file or directory
   16 | #include <rpc/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

[ 82%] Building CXX object ogr/ogrsf_frmts/ogdi/CMakeFiles/ogr_OGDI.dir/ogrogdidatasource.cpp.o
In file included from /home/werdna/git/gdal/ogr/ogrsf_frmts/ogdi/ogrogdi.h:40,
                 from /home/werdna/git/gdal/ogr/ogrsf_frmts/ogdi/ogrogdidatasource.cpp:30:
/usr/include/ogdi/ecs.h:9:10: fatal error: rpc/rpc.h: No such file or directory
    9 | #include <rpc/rpc.h>
      |          ^~~~~~~~~~~
compilation terminated.

## Steps to reproduce the problem.
cd ~/gdal/source
git pull
cmake -S ~/gdal/source -B ~/gdal/build
cd ~/gdal/build
make -k

## Operating system
Ubunto 21.10, impish (tested on 64bit)

## GDAL version and provenance
github master as at 12 Nov 2021 ab14711

I am happy to look at this, but I have no experience of either cmake or pkgconfig.

**Comment by rouault** [comment]
DODS support will be dropped in GDAL 3.5, so you can leave that out and build with cmake .. -DGDAL_USE_DAP=OFF to disable it.
Regarding OGDI, it should be a matter of tweaking cmake/modules/packages/FindOGDI.cmake to use pkg-config . You can have a look at cmake/modules/packages/FindJXL.cmake
