### ISSUE TITLE
issue installing gdal python3 module 2.3.1

### ISSUE THREAD

**Issue by emorthen** [OSGeo/gdal#880]
## Expected behavior and actual behavior.
Related to https://github.com/OSGeo/gdal/issues/674
Should be able to `brew install gdal`, followed by `pip3 install gdal`
Result from `export PYTHONPATH=/usr/local/Cellar/gdal/2.3.1_1/lib/python3.7/site-packages`, followed by  `sudo pip3 install gdal`:
```
Collecting gdal==2.3.1
  Downloading https://files.pythonhosted.org/packages/99/31/2e05c1be3196126fa04028aed51489f40ceea77e8361a80bc8b00fc463db/GDAL-2.3.1.tar.gz (557kB)
    100% |████████████████████████████████| 563kB 4.0MB/s 
Installing collected packages: gdal
  Running setup.py install for gdal ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-l56152z7/gdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-1czy04on/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-3.6
    copying gdal.py -> build/lib.macosx-10.6-intel-3.6
    copying ogr.py -> build/lib.macosx-10.6-intel-3.6
    copying osr.py -> build/lib.macosx-10.6-intel-3.6
    copying gdalconst.py -> build/lib.macosx-10.6-intel-3.6
    copying gnm.py -> build/lib.macosx-10.6-intel-3.6
    copying gdalnumeric.py -> build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/gnm.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/__init__.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/gdalnumeric.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/osr.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/gdal.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/ogr.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/gdal_array.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    copying osgeo/gdalconst.py -> build/lib.macosx-10.6-intel-3.6/osgeo
    Fixing build/lib.macosx-10.6-intel-3.6/gdal.py build/lib.macosx-10.6-intel-3.6/ogr.py build/lib.macosx-10.6-intel-3.6/osr.py build/lib.macosx-10.6-intel-3.6/gdalconst.py build/lib.macosx-10.6-intel-3.6/gnm.py build/lib.macosx-10.6-intel-3.6/gdalnumeric.py build/lib.macosx-10.6-intel-3.6/osgeo/gnm.py build/lib.macosx-10.6-intel-3.6/osgeo/__init__.py build/lib.macosx-10.6-intel-3.6/osgeo/gdalnumeric.py build/lib.macosx-10.6-intel-3.6/osgeo/osr.py build/lib.macosx-10.6-intel-3.6/osgeo/gdal.py build/lib.macosx-10.6-intel-3.6/osgeo/ogr.py build/lib.macosx-10.6-intel-3.6/osgeo/gdal_array.py build/lib.macosx-10.6-intel-3.6/osgeo/gdalconst.py
    Skipping optional fixer: ws_comma
    Fixing build/lib.macosx-10.6-intel-3.6/gdal.py build/lib.macosx-10.6-intel-3.6/ogr.py build/lib.macosx-10.6-intel-3.6/osr.py build/lib.macosx-10.6-intel-3.6/gdalconst.py build/lib.macosx-10.6-intel-3.6/gnm.py build/lib.macosx-10.6-intel-3.6/gdalnumeric.py build/lib.macosx-10.6-intel-3.6/osgeo/gnm.py build/lib.macosx-10.6-intel-3.6/osgeo/__init__.py build/lib.macosx-10.6-intel-3.6/osgeo/gdalnumeric.py build/lib.macosx-10.6-intel-3.6/osgeo/osr.py build/lib.macosx-10.6-intel-3.6/osgeo/gdal.py build/lib.macosx-10.6-intel-3.6/osgeo/ogr.py build/lib.macosx-10.6-intel-3.6/osgeo/gdal_array.py build/lib.macosx-10.6-intel-3.6/osgeo/gdalconst.py
    Skipping optional fixer: ws_comma
    running build_ext
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o -std=c++11
    building 'osgeo._gdal' extension
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/extensions
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/extensions/gdal_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/gdal_wrap.cpp:3169:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    3 warnings generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future build/temp.macosx-10.6-intel-3.6/extensions/gdal_wrap.o -L../../.libs -L../../ -L/usr/local/Cellar/gdal/2.3.1_1/lib -lgdal -o build/lib.macosx-10.6-intel-3.6/osgeo/_gdal.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: warning: directory not found for option '-L../../.libs'
    building 'osgeo._gdalconst' extension
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/gdalconst_wrap.c -o build/temp.macosx-10.6-intel-3.6/extensions/gdalconst_wrap.o -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/gdalconst_wrap.c:3021:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal.h:45:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    3 warnings generated.
    /usr/bin/clang -bundle -undefined dynamic_lookup -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future build/temp.macosx-10.6-intel-3.6/extensions/gdalconst_wrap.o -L../../.libs -L../../ -L/usr/local/Cellar/gdal/2.3.1_1/lib -lgdal -o build/lib.macosx-10.6-intel-3.6/osgeo/_gdalconst.cpython-36m-darwin.so
    ld: warning: directory not found for option '-L../../.libs'
    building 'osgeo._osr' extension
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/osr_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/extensions/osr_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/osr_wrap.cpp:3193:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_string.h:35:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_error.h:34:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    extensions/osr_wrap.cpp:3412:10: warning: explicitly assigning value of variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
        self = self;
        ~~~~ ^ ~~~~
    extensions/osr_wrap.cpp:3413:10: warning: explicitly assigning value of variable of type 'PyObject *' (aka '_object *') to itself [-Wself-assign]
        args = args;
        ~~~~ ^ ~~~~
    5 warnings generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future build/temp.macosx-10.6-intel-3.6/extensions/osr_wrap.o -L../../.libs -L../../ -L/usr/local/Cellar/gdal/2.3.1_1/lib -lgdal -o build/lib.macosx-10.6-intel-3.6/osgeo/_osr.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: warning: directory not found for option '-L../../.libs'
    building 'osgeo._ogr' extension
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/ogr_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/extensions/ogr_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/ogr_wrap.cpp:3151:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal.h:45:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    3 warnings generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future build/temp.macosx-10.6-intel-3.6/extensions/ogr_wrap.o -L../../.libs -L../../ -L/usr/local/Cellar/gdal/2.3.1_1/lib -lgdal -o build/lib.macosx-10.6-intel-3.6/osgeo/_ogr.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: warning: directory not found for option '-L../../.libs'
    building 'osgeo._gnm' extension
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/gnm_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/extensions/gnm_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/gnm_wrap.cpp:3138:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal.h:45:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    3 warnings generated.
    /usr/bin/clang++ -bundle -undefined dynamic_lookup -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future build/temp.macosx-10.6-intel-3.6/extensions/gnm_wrap.o -L../../.libs -L../../ -L/usr/local/Cellar/gdal/2.3.1_1/lib -lgdal -o build/lib.macosx-10.6-intel-3.6/osgeo/_gnm.cpython-36m-darwin.so
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    ld: warning: directory not found for option '-L../../.libs'
    building 'osgeo._gdal_array' extension
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -g -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include -I/usr/local/Cellar/gdal/2.3.1_1/include -c extensions/gdal_array_wrap.cpp -o build/temp.macosx-10.6-intel-3.6/extensions/gdal_array_wrap.o -std=c++11 -I/usr/local/Cellar/gdal/2.3.1_1/include
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
    In file included from extensions/gdal_array_wrap.cpp:3143:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal.h:45:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/cpl_port.h:66:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_config.h:104:9: warning: 'HAVE_LONG_LONG' macro redefined [-Wmacro-redefined]
    #define HAVE_LONG_LONG 1
            ^
    /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m/pyport.h:42:9: note: previous definition is here
    #define HAVE_LONG_LONG
            ^
    In file included from extensions/gdal_array_wrap.cpp:3143:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal.h:49:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_minixml.h:202:37: error: unknown template name 'unique_ptr'
    class CPLXMLTreeCloser: public std::unique_ptr<CPLXMLNode, CPLXMLTreeCloserDeleter>
                                        ^
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_minixml.h:207:20: error: expected '(' or '{'
        std::unique_ptr<CPLXMLNode, CPLXMLTreeCloserDeleter>(data) {}
                       ^
    In file included from extensions/gdal_array_wrap.cpp:3461:
    In file included from /usr/local/Cellar/gdal/2.3.1_1/include/gdal_priv.h:63:
    /usr/local/Cellar/gdal/2.3.1_1/include/cpl_conv.h:372:10: fatal error: 'type_traits' file not found
    #include <type_traits> // for std::is_base_of
             ^~~~~~~~~~~~~
    3 warnings and 3 errors generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-install-l56152z7/gdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-1czy04on/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-install-l56152z7/gdal/
```

## Steps to reproduce the problem.
`brew install gdal`
`sudo pip3 install gdal`

Also tried with `export PYTHONPATH=/usr/local/Cellar/gdal/2.3.1_1/lib/python3.7/site-packages`
## Operating system

OS X High Sierra 10.13.6

## GDAL version and provenance
2.3.1_1 

## Notes
Installation worked fine with python 2.7

**Comment by rouault** [comment]
I'm not a mac user, so can't really help. What I notice is that there's no -std=c++11 flag when invoking clang++. This might be fine if the default C++ version of your clang version is C++11 or later. If not, then that's the issue. Normally setup.py should add the -std=c++11 flag.

It seems weird to me that this works with python 2.7 and not with 3.6. Perhaps this is not the same compiler invoked ?

**Comment by HryKlein** [comment]
Indeed, after some research I discovered some strange python configuration, so the error might just as well be caused by this.

**Comment by rich-lopez** [comment]
@HryKlein did you resolve your issue? If so, could you share what changes you made to fix the problem? I am seeing the identical problem.

**Comment by arkadybag** [comment]
https://stackoverflow.com/questions/31107638/python-gdal-installation-by-pip-fails

**Comment by rcoup** [comment]
One way (also works cleanly in virtualenvs/etc) is to use [pygdal](https://pypi.org/project/pygdal/):
```
$ brew install gdal
$ pip install pygdal=="$(gdal-config --version).*"
```

**Comment by Prakashvanapalli** [comment]
@rcoup this install gdal=2.2.2 version. I need gdal 3.0.4 verion. is there a way to download that. thanks

**Comment by zwarshavsky** [comment]
I am experiencing the same issue. Looking to install gdal 3.1.3. `pygdal` install failed with the same error.
