### PR TITLE
Build: fix build against Poppler 25.02.00

### LINKED ISSUE #11804: [3.10.1] fails to build with poppler-25.02.0
### What is the bug?

3.10.1 fails to build with poppler-25.02.0:

>[ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidsk_tex.cpp.o
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp: In member function ‘CPLErr PDFDataset::ReadPixels(int, int, int, int, GSpacing, GSpacing, GSpacing, GByte*)’:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:1978:38: error: cannot convert ‘std::unique_ptr<OCGs>’ to ‘OCGs*’ in initialization
   1978 |         OCGs *poOldOCGs = poCatalog->optContent;
        |                           ~~~~~~~~~~~^~~~~~~~~~
        |                                      |
        |                                      std::unique_ptr<OCGs>
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:1992:37: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<OCGs>’ and ‘OCGs*’)
   1992 |             poCatalog->optContent = poOldOCGs;
        |                                     ^~~~~~~~~
  In file included from /usr/include/c++/14.2.0/memory:78,
                   from /usr/include/poppler/goo/GooString.h:45,
                   from /usr/include/poppler/Object.h:45:
  /usr/include/c++/14.2.0/bits/unique_ptr.h:424:9: note: candidate: ‘template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::__uniq_ptr_impl<_Tp, _Dp>::pointer>, std::__not_<std::is_array<_Up> > >, std::is_assignable<_Dp&, _Ep&&> >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Ep = _Up; _Tp = OCGs; _Dp = std::default_delete<OCGs>]’
    424 |         operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
        |         ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:424:9: note:   template argument deduction/substitution failed:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:1992:37: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘OCGs*’
   1992 |             poCatalog->optContent = poOldOCGs;
        |                                     ^~~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:408:19: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = OCGs; _Dp = std::default_delete<OCGs>]’
    408 |       unique_ptr& operator=(unique_ptr&&) = default;
        |                   ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:408:29: note:   no known conversion for argument 1 from ‘OCGs*’ to ‘std::unique_ptr<OCGs>&&’
    408 |       unique_ptr& operator=(unique_ptr&&) = default;
        |                             ^~~~~~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:434:7: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = OCGs; _Dp = std::default_delete<OCGs>; std::nullptr_t = std::nullptr_t]
    434 |       operator=(nullptr_t) noexcept
        |       ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:434:17: note:   no known conversion for argument 1 from ‘OCGs*’ to ‘std::nullptr_t’
    434 |       operator=(nullptr_t) noexcept
        |                 ^~~~~~~~~
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:1998:33: error: no match for ‘operator=’ (operand types are ‘std::unique_ptr<OCGs>’ and ‘OCGs*’)
   1998 |         poCatalog->optContent = poOldOCGs;
        |                                 ^~~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:424:9: note: candidate: ‘template<class _Up, class _Ep> typename std::enable_if<std::__and_<std::__and_<std::is_convertible<typename std::unique_ptr<_Up, _Ep>::pointer, typename std::__uniq_ptr_impl<_Tp, _Dp>::pointer>, std::__not_<std::is_array<_Up> > >, std::is_assignable<_Dp&, _Ep&&> >::value, std::unique_ptr<_Tp, _Dp>&>::type std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Ep = _Up; _Tp = OCGs; _Dp = std::default_delete<OCGs>]’
    424 |         operator=(unique_ptr<_Up, _Ep>&& __u) noexcept
        |         ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:424:9: note:   template argument deduction/substitution failed:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:1998:33: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘OCGs*’
   1998 |         poCatalog->optContent = poOldOCGs;
        |                                 ^~~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:408:19: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::unique_ptr<_Tp, _Dp>&&) [with _Tp = OCGs; _Dp = std::default_delete<OCGs>]’
    408 |       unique_ptr& operator=(unique_ptr&&) = default;
        |                   ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:408:29: note:   no known conversion for argument 1 from ‘OCGs*’ to ‘std::unique_ptr<OCGs>&&’
    408 |       unique_ptr& operator=(unique_ptr&&) = default;
        |                             ^~~~~~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:434:7: note: candidate: ‘std::unique_ptr<_Tp, _Dp>& std::unique_ptr<_Tp, _Dp>::operator=(std::nullptr_t) [with _Tp = OCGs; _Dp = std::default_delete<OCGs>; std::nullptr_t = std::nullptr_t]’
    434 |       operator=(nullptr_t) noexcept
        |       ^~~~~~~~
  /usr/include/c++/14.2.0/bits/unique_ptr.h:434:17: note:   no known conversion for argument 1 from ‘OCGs*’ to ‘std::nullptr_t’
    434 |       operator=(nullptr_t) noexcept
        |                 ^~~~~~~~~
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp: In member function ‘void PDFDataset::ExploreLayersPoppler(GDALPDFArray*, int, int, CPLString, int, int&, bool&)’:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:3739:77: error: invalid conversion from ‘const OCGs*’ to ‘OCGs*’ [-fpermissive]
   3739 |                 OCGs *optContentConfig = m_poDocPoppler->getOptContentConfig();
        |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
        |                                                                             |
        |                                                                             const OCGs*
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp: In member function ‘void PDFDataset::FindLayersPoppler(int)’:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:3775:65: error: invalid conversion from ‘const OCGs*’ to ‘OCGs*’ [-fpermissive]
   3775 |     OCGs *optContentConfig = m_poDocPoppler->getOptContentConfig();
        |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
        |                                                                 |
        |                                                                 const OCGs*
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:3779:51: error: invalid conversion from ‘const Array*’ to ‘Array*’ [-fpermissive]
   3779 |     Array *array = optContentConfig->getOrderArray();
        |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
        |                                                   |
        |                                                   const Array*
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp: In member function ‘void PDFDataset::TurnLayersOnOffPoppler()’:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfdataset.cpp:3815:65: error: invalid conversion from ‘const OCGs*’ to ‘OCGs*’ [-fpermissive]
   3815 |     OCGs *optContentConfig = m_poDocPoppler->getOptContentConfig();
        |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
        |                                                                 |
        |                                                                 const OCGs*
  [ 41%] Building CXX object frmts/pdf/CMakeFiles/gdal_PDF.dir/pdfio.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskbinarysegment.cpp.o
  make[2]: *** [frmts/pdf/CMakeFiles/gdal_PDF.dir/build.make:107: frmts/pdf/CMakeFiles/gdal_PDF.dir/pdfdataset.cpp.o] Error 1
  make[2]: *** Waiting for unfinished jobs....
  [ 41%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/gmlcoverage.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskbitmap.cpp.o
  [ 41%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskblut.cpp.o
  [ 41%] Building CXX object frmts/http/CMakeFiles/gdal_HTTP.dir/httpdriver.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskpct.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskephemerissegment.cpp.o
  [ 41%] Built target gdal_HTTP
  [ 41%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset100.cpp.o
  [ 41%] Building CXX object frmts/pcidsk/sdk/CMakeFiles/pcidsk_sdk.dir/segment/cpcidskgcp2segment.cpp.o
  In file included from /home/SBo/gdal-3.10.1/frmts/pdf/pdfio.cpp:17:
  /home/SBo/gdal-3.10.1/frmts/pdf/pdfio.h:51:18: error: conflicting return type specified for ‘virtual void VSIPDFFileStream::reset()’
     51 |     virtual void reset() override;
        |                  ^~~~~
  In file included from /usr/include/poppler/Object.h:596,
                   from /home/SBo/gdal-3.10.1/frmts/pdf/pdfsdk_headers_poppler.h:45,
                   from /home/SBo/gdal-3.10.1/frmts/pdf/pdfsdk_headers_all.h:20,
                   from /home/SBo/gdal-3.10.1/frmts/pdf/gdal_pdf.h:39,
                   from /home/SBo/gdal-3.10.1/frmts/pdf/pdfio.cpp:13:
  /usr/include/poppler/Stream.h:129:18: note: overridden function is ‘virtual bool Stream::reset()’
    129 |     virtual bool reset() = 0;
        |                  ^~~~~
  make[2]: *** [frmts/pdf/CMakeFiles/gdal_PDF.dir/build.make:121: frmts/pdf/CMakeFiles/gdal_PDF.dir/pdfio.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:8080: frmts/pdf/CMakeFiles/gdal_PDF.dir/all] Error 2`

### Steps to reproduce the issue

see https://github.com/OSGeo/gdal/issues/11477

### Versions and provenance

Slackware Linux: slackware64-current (as of 5 Feb 2025)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #11804

### CODE REVIEW

**Comment by rouault** [comment]
@dbaston  / @elpaso : can you approve this?  (as Poppler 25.02 starts being deployed in some of our CI) thanks

**Review by elpaso — APPROVED** [review]
