### ISSUE TITLE
gdal-3.12.3 build fails with error: cannot convert ‘const std::string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const GooString*’ in initialization

### ISSUE THREAD

**Issue by xelaseer** [OSGeo/gdal#14341]
### What is the bug?

As per the above, gdal-3.12.3 fails with fails with error: 

/var/tmp/portage/sci-libs/gdal-3.12.3/work/gdal-3.12.3/frmts/pdf/pdfobject.cpp: In member function ‘virtual const std::string& GDALPDFObjectPoppler::GetString()’:
/var/tmp/portage/sci-libs/gdal-3.12.3/work/gdal-3.12.3/frmts/pdf/pdfobject.cpp:1125:58: error: cannot convert ‘const std::string’ {aka ‘const std::__cxx11::basic_string<char>’} to ‘const GooString*’ in initialization
 1125 |         const GooString *gooString = m_poConst->getString();
      |                                      ~~~~~~~~~~~~~~~~~~~~^~
      |                                                          |
      |                                                          const std::string {aka const std::__cxx11::basic_string<char>}

Further information is in the attached files.

[build.log](https://github.com/user-attachments/files/26669291/build.log)

### Steps to reproduce the issue

1. Build with Gentoo and GCC 16.0.1
2. Fail

### Versions and provenance

Gentoo ~amd64 - systemd/gnome stack

GDAL-3.12.3

GCC 16.0.1

[emerge-info.txt](https://github.com/user-attachments/files/26669281/emerge-info.txt)

**Comment by rouault** [comment]
you need to apply 0ad9529d5fd5e03880147221d56bfee08383d7dc
